//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PressfordNewsSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article1
    {
        public int ArticleID { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Body { get; set; }
        public string AuthorID { get; set; }
        public string DatePublished { get; set; }
    }
}
